export const THEMES = [
  {
    name: "light",
    label: "Light",
    colors: ["#ffffff", "#5a67d8", "#8b5cf6", "#1a202c"],
  },
  {
    name: "dark",
    label: "Dark",
    colors: ["#1f2937", "#8b5cf6", "#ec4899", "#1a202c"],
  },
  {
    name: "cupcake",
    label: "Cupcake",
    colors: ["#f5f5f4", "#65c3c8", "#ef9fbc", "#291334"],
  },
  {
    name: "forest",
    label: "Forest",
    colors: ["#1f1d1d", "#3ebc96", "#70c217", "#e2e8f0"],
  },
  {
    name: "bumblebee",
    label: "Bumblebee",
    colors: ["#ffffff", "#f8e36f", "#f0d50c", "#1c1917"],
  },
  {
    name: "emerald",
    label: "Emerald",
    colors: ["#ffffff", "#66cc8a", "#3b82f6", "#1e3a8a"],
  },
  {
    name: "corporate",
    label: "Corporate",
    colors: ["#ffffff", "#4b6bfb", "#7b92b2", "#1d232a"],
  },
  {
    name: "synthwave",
    label: "Synthwave",
    colors: ["#2d1b69", "#e779c1", "#58c7f3", "#f8f8f2"],
  },
  {
    name: "retro",
    label: "Retro",
    colors: ["#e4d8b4", "#ea6962", "#6aaa64", "#282425"],
  },
  {
    name: "cyberpunk",
    label: "Cyberpunk",
    colors: ["#ffee00", "#ff7598", "#75d1f0", "#1a103d"],
  },
  {
    name: "valentine",
    label: "Valentine",
    colors: ["#f0d6e8", "#e96d7b", "#a991f7", "#37243c"],
  },
  {
    name: "halloween",
    label: "Halloween",
    colors: ["#0d0d0d", "#ff7800", "#006400", "#ffffff"],
  },
  {
    name: "garden",
    label: "Garden",
    colors: ["#e9e7e7", "#ec4899", "#16a34a", "#374151"],
  },

  {
    name: "aqua",
    label: "Aqua",
    colors: ["#193549", "#4cd4e3", "#9059ff", "#f8d766"],
  },
  {
    name: "lofi",
    label: "Lofi",
    colors: ["#0f0f0f", "#1a1919", "#232323", "#2c2c2c"],
  },
  {
    name: "pastel",
    label: "Pastel",
    colors: ["#f7f3f5", "#d1c1d7", "#a1e3d8", "#4a98f1"],
  },
  {
    name: "fantasy",
    label: "Fantasy",
    colors: ["#ffe7d6", "#a21caf", "#3b82f6", "#f59e0b"],
  },
  {
    name: "wireframe",
    label: "Wireframe",
    colors: ["#e6e6e6", "#b3b3b3", "#b3b3b3", "#888888"],
  },
  {
    name: "black",
    label: "Black",
    colors: ["#000000", "#191919", "#313131", "#4a4a4a"],
  },
  {
    name: "luxury",
    label: "Luxury",
    colors: ["#171618", "#1e293b", "#94589c", "#d4a85a"],
  },
  {
    name: "dracula",
    label: "Dracula",
    colors: ["#282a36", "#ff79c6", "#bd93f9", "#f8f8f2"],
  },
  {
    name: "cmyk",
    label: "CMYK",
    colors: ["#f0f0f0", "#0891b2", "#ec4899", "#facc15"],
  },
  {
    name: "autumn",
    label: "Autumn",
    colors: ["#f2f2f2", "#8c1f11", "#f28c18", "#6f4930"],
  },
  {
    name: "business",
    label: "Business",
    colors: ["#f5f5f5", "#1e40af", "#3b82f6", "#f97316"],
  },
  {
    name: "acid",
    label: "Acid",
    colors: ["#110e0e", "#ff00f2", "#ff7a00", "#99ff01"],
  },
  {
    name: "lemonade",
    label: "Lemonade",
    colors: ["#ffffff", "#67e8f9", "#f5d742", "#2c3333"],
  },
  {
    name: "night",
    label: "Night",
    colors: ["#0f172a", "#38bdf8", "#818cf8", "#e2e8f0"],
  },
  {
    name: "coffee",
    label: "Coffee",
    colors: ["#20161f", "#dd9866", "#497174", "#eeeeee"],
  },
  {
    name: "winter",
    label: "Winter",
    colors: ["#ffffff", "#0284c7", "#d946ef", "#0f172a"],
  },
  {
    name: "dim",
    label: "Dim",
    colors: ["#1c1c27", "#10b981", "#ff5a5f", "#0f172a"],
  },
  {
    name: "nord",
    label: "Nord",
    colors: ["#eceff4", "#5e81ac", "#81a1c1", "#3b4252"],
  },
  {
    name: "sunset",
    label: "Sunset",
    colors: ["#1e293b", "#f5734c", "#ec4899", "#ffffff"],
  },
];

export const LANGUAGES = [
  "English",
  "Spanish",
  "French",
  "German",
  "Mandarin",
  "Japanese",
  "Korean",
  "Hindi",
  "Russian",
  "Portuguese",
  "Arabic",
  "Italian",
  "Turkish",
  "Dutch",
];

export const SINGERS = [
  "A R Rahman",
  "Aditya Narayan",
  "Alka Yagnik",
  "Alok",
  "Anirudh Ravichander",
  "Ankit Tiwari",
  "Anuradha Paudwal",
  "Arijit Singh",
  "Armaan Malik",
  "Atif Aslam",
  "Bad Bunny",
  "Benny Dayal",
  "Beyoncé",
  "Billie Eilish",
  "Bruno Mars",
  "Charlie Puth",
  "Darshan Raval",
  "Diljit Dosanjh",
  "Doja Cat",
  "Drake",
  "Dua Lipa",
  "Ed Sheeran",
  "Elton John",
  "Elvis Presley",
  "Eminem",
  "Gippy Grewal",
  "Guru Randhawa",
  "Harrdy Sandhu",
  "Harry Styles",
  "Jasleen Royal",
  "Jubin Nautiyal",
  "Justin Bieber",
  "Justin Timberlake",
  "Katy Perry",
  "KK",
  "Kumar Sanu",
  "Lady Gaga",
  "Lata Mangeshkar",
  "Madhushree",
  "Madonna",
  "Maninder Buttar",
  "Mariah Carey",
  "Mika Singh",
  "Miley Cyrus",
  "Mohit Chauhan",
  "Monali Thakur",
  "Neha Kakkar",
  "Nikhita Gandhi",
  "Nicki Minaj",
  "Nora Fatehi",
  "Olivia Rodrigo",
  "Palak Muchhal",
  "Papon",
  "Prateek Kuhad",
  "Rahat Fateh Ali Khan",
  "Rahul Vaidya",
  "Rihanna",
  "Sachet Tandon",
  "Salim Merchant",
  "Sam Smith",
  "Sanam Puri",
  "Shaan",
  "Shankar Mahadevan",
  "Shawn Mendes",
  "Shekhar Ravjiani",
  "Shilpa Rao",
  "Shreya Ghoshal",
  "Sidhu Moose Wala",
  "Sia",
  "Sonu Nigam",
  "Stevie Wonder",
  "Sunidhi Chauhan",
  "Taylor Swift",
  "The Weeknd",
  "Tony Kakkar",
  "Tulsi Kumar",
  "Udit Narayan",
  "Usher",
  "Vishal Dadlani",
  "Whitney Houston",
  "Yo Yo Honey Singh",
  "Zara Larsson",
  "Zayn Malik",
  "Adnan Sami",
  "Anoushka Shankar",
  "Bhupinder Singh",
  "Gurdas Maan",
  "Jagjit Singh",
  "Kailash Kher",
  "Lucky Ali",
  "Mehdi Hassan",
  "Nusrat Fateh Ali Khan",
  "Pankaj Udhas",
  "Rekha Bhardwaj",
  "S. P. Balasubrahmanyam",
  "Talat Aziz",
  "Vishal Mishra",
  "Yesudas",
];


export const LANGUAGE_TO_FLAG = {
  english: "gb",
  spanish: "es",
  french: "fr",
  german: "de",
  mandarin: "cn",
  japanese: "jp",
  korean: "kr",
  hindi: "in",
  russian: "ru",
  portuguese: "pt",
  arabic: "sa",
  italian: "it",
  turkish: "tr",
  dutch: "nl",
};

export const SINGER_TO_FLAG = {
  "A R Rahman": "in",
  "Aditya Narayan": "in",
  "Alka Yagnik": "in",
  "Alok": "pt",
  "Anirudh Ravichander": "in",
  "Ankit Tiwari": "in",
  "Anuradha Paudwal": "in",
  "Arijit Singh": "in",
  "Armaan Malik": "in",
  "Atif Aslam": "in",
  "Bad Bunny": "es",
  "Benny Dayal": "in",
  "Beyoncé": "gb",
  "Billie Eilish": "gb",
  "Bruno Mars": "pt",
  "Charlie Puth": "gb",
  "Darshan Raval": "in",
  "Diljit Dosanjh": "in",
  "Doja Cat": "gb",
  "Drake": "gb",
  "Dua Lipa": "gb",
  "Ed Sheeran": "gb",
  "Elton John": "gb",
  "Elvis Presley": "gb",
  "Eminem": "gb",
  "Gippy Grewal": "in",
  "Guru Randhawa": "in",
  "Harrdy Sandhu": "in",
  "Harry Styles": "gb",
  "Jasleen Royal": "in",
  "Jubin Nautiyal": "in",
  "Justin Bieber": "gb",
  "Justin Timberlake": "gb",
  "Katy Perry": "gb",
  "KK": "in",
  "Kumar Sanu": "in",
  "Lady Gaga": "gb",
  "Lata Mangeshkar": "in",
  "Madhushree": "in",
  "Madonna": "gb",
  "Maninder Buttar": "in",
  "Mariah Carey": "gb",
  "Mika Singh": "in",
  "Miley Cyrus": "gb",
  "Mohit Chauhan": "in",
  "Monali Thakur": "in",
  "Neha Kakkar": "in",
  "Nikhita Gandhi": "in",
  "Nicki Minaj": "gb",
  "Nora Fatehi": "in",
  "Olivia Rodrigo": "gb",
  "Palak Muchhal": "in",
  "Papon": "in",
  "Prateek Kuhad": "in",
  "Rahat Fateh Ali Khan": "in",
  "Rahul Vaidya": "in",
  "Rihanna": "gb",
  "Sachet Tandon": "in",
  "Salim Merchant": "in",
  "Sam Smith": "gb",
  "Sanam Puri": "in",
  "Shaan": "in",
  "Shankar Mahadevan": "in",
  "Shawn Mendes": "gb",
  "Shekhar Ravjiani": "in",
  "Shilpa Rao": "in",
  "Shreya Ghoshal": "in",
  "Sidhu Moose Wala": "in",
  "Sia": "gb",
  "Sonu Nigam": "in",
  "Stevie Wonder": "gb",
  "Sunidhi Chauhan": "in",
  "Taylor Swift": "gb",
  "The Weeknd": "gb",
  "Tony Kakkar": "in",
  "Tulsi Kumar": "in",
  "Udit Narayan": "in",
  "Usher": "gb",
  "Vishal Dadlani": "in",
  "Whitney Houston": "gb",
  "Yo Yo Honey Singh": "in",
  "Zara Larsson": "nl",
  "Zayn Malik": "gb",
  "Adnan Sami": "in",
  "Anoushka Shankar": "in",
  "Bhupinder Singh": "in",
  "Gurdas Maan": "in",
  "Jagjit Singh": "in",
  "Kailash Kher": "in",
  "Lucky Ali": "in",
  "Mehdi Hassan": "in",
  "Nusrat Fateh Ali Khan": "in",
  "Pankaj Udhas": "in",
  "Rekha Bhardwaj": "in",
  "S. P. Balasubrahmanyam": "in",
  "Talat Aziz": "in",
  "Vishal Mishra": "in",
  "Yesudas": "in",
};
